## Environment ##
ami_owners: 
  - <AMI owner>
ami_filters:
  - <AMI filter selector pattern 01>
  - ..
  - <AMI filter selector pattern n>
ami_filter_by: <AMI selector criteria>
cloud_init_file_path: <cloud-init file template path>
instance_type: <Instance type, must be compatible with AMI type>
key_pair_name: <SSH Key, public>
listening_ports_protocols: 
  - port: <Port>
    protocol: <Protocol>
    inbound_cidrs: 
      - <CIDR with SSH access 01>
      - ...
      - <CIDR with SSH access n>
subnet_filter_criteria: <Subnet filter criteria>
subnet_filter_values:
  - <Subnet filter values, 0>
subnet_id_public:
  - <Public subnet 01...ALB external facade>
  - ...
  - <Public subnet n .. ALB external facade>
vpc_id: <VPC hosting the instance> 

## Tags ##
tags_common:
  account_id: <Account id.>
  environment: <development, production, laboratory...>
  business_unit: <Responsible dept.>
  service_name: <AWS service name: lambda, ec2, vpc...>
  service_resource: <AWS service resource: bucket, instance, ami...>
  purpose: <Intended use>
  region: <Region>
